image: docker:1.11.2

stages:
- build
- test
- prerelease
- release

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:CI_BUILD_REF_NAME .

test-http2:
  stage: test
  script:
    - docker run --rm $CI_REGISTRY_IMAGE:CI_BUILD_REF_NAME -s --http2 -I https://nghttp2.org

prerelease:
  stage: prerelease
  script:
    - docker push $CI_REGISTRY_IMAGE:CI_BUILD_REF_NAME

release-version:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE:CI_BUILD_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:CI_BUILD_REF_NAME $CI_REGISTRY_IMAGE:$(cat VERSION)
    - docker push $CI_REGISTRY_IMAGE:$(cat VERSION)
  only:
    - master

release-latest:
  stage: release
  script:
    - docker pull $CI_REGISTRY_IMAGE:CI_BUILD_REF_NAME
    - docker tag $CI_REGISTRY_IMAGE:CI_BUILD_REF_NAME $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
  only:
    - master
